COLLECT_MEASUREMENTS = False
MEASUREMENT_FOLDER = '/home/pi/Downloads/AOA-Localization/raspberry-pi/measurements'
CONFIG_FOLDER = '/home/pi/Downloads/AOA-Localization/raspberry-pi/config'
GATEWAY_IP = '10.42.0.1'
INGRESS_SERVER_PORT = 9901
EGRESS_PORT = 9902
SUBSCRIPTION_PORT = 9903
BUFFER_SIZE=8192
MAX_BUFFER_SIZE = 8